version: '3'
services:
    mailcatcher:
        ports:
            - 1080:1080
        container_name: mailcatcher
        image: schickling/mailcatcher

    ### auth service
    fpm-auth:
        container_name: fpm-auth
        image: devilbox/php-fpm-7.4:latest
        depends_on:
            - mailcatcher
        volumes:
            - ./auth:/var/www/html
            - .docker/.bashrc:/root/.bashrc
        build:
            context: .docker/php
        environment:
            APP_ENV: 'dev'
            APP_SECRET: '5efe1ac31fa0e2ea650649a345a1cd83'
            DATABASE_URL: 'sqlite:///%kernel.project_dir%/var/sqlite.db'
            MAILER_URL: 'smtp://mailcatcher:1025?encryption=&auth_mode='

    nginx-auth:
        container_name: nginx-auth
        image: nginx
        volumes:
            - .docker/nginx-auth.conf:/etc/nginx/conf.d/default.conf
            - .docker/.bashrc:/root/.bashrc
        links:
            - fpm-auth
        ports:
            - 8000:8000

    ### api service
    fpm-api:
        container_name: fpm-api
        image: devilbox/php-fpm-7.4:latest
        depends_on:
            - nginx-auth
        volumes:
            - ./api:/var/www/html
            - .docker/.bashrc:/root/.bashrc
        build:
            context: .docker/php
        environment:
            APP_ENV: 'dev'
            APP_SECRET: '5efe1ac31fa0e2ea650649a345a1cd83'
            CORS_ALLOW_ORIGIN_DOMAIN: 'localhost'

    nginx-api:
        container_name: nginx-api
        image: nginx
        volumes:
            - .docker/nginx-api.conf:/etc/nginx/conf.d/default.conf
            - .docker/.bashrc:/root/.bashrc
        links:
            - fpm-api
        ports:
            - 8001:8001

    nginx-frontend:
        container_name: nginx-frontend
        image: nginx
        volumes:
            - ./frontend:/var/www/html
            - .docker/nginx-frontend.conf:/etc/nginx/conf.d/default.conf
            - .docker/.bashrc:/root/.bashrc
        ports:
            - 8008:8008
